version: '2.4'
services:

  artifactory:
    container_name: artifactory
    image: docker.bintray.io/jfrog/artifactory-jcr:latest
    ports:
      - 8081:8081
      - 8082:8082
    volumes:
      - "./artifactory:/artifactory_extra_conf/"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/artifactory/api/system/ping"]
      interval: 5s
      timeout: 10s
      retries: 30

  jenkins:
    depends_on:
      artifactory:
        condition: service_healthy
    container_name: jenkins
    build: "./jenkins_controller"
    ports:
      - "8880:8080"
      - "50000:50000"
    volumes:
      - "./jenkins_controller/casc.yml:/usr/share/jenkins/ref/casc.yml"
    restart: always

  jenkins_agent:
    depends_on:
        - jenkins
    container_name: jenkins_agent
    build: "./jenkins_agent"
    ports:
      - "2222:22"
    volumes:
      - "./var/run/docker.sock:/var/run/docker.sock"
    restart: always
    environment:
      JENKINS_AGENT_SSH_PUBKEY: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDkttmpKDrYOWKKCLLhztIpBVMlAmTj48PsxzPEg9kuANM+JC64e0waDwU8EnA7QYEmocPNVxrfX7WxNZA4B3eur3DbTDfPfo2gggZBzbAqdEDUI7zHh4VBKgTtmcJl9JD9U5z5ev6ovpuH3Sp8acGl4Ar/jCtoMje5BfzJOk74cXFbvQpkdW5EJpuipiZhZHhxLZGRxemkg8ok2EjN5Ys6XzwnMaYp0br9sJDtOqJi4+0AqxrxbSWEjb54eoBx6heDtS10O714stxF8nU1BgQ0scdYACt7+no5wCwBHYPIiYivv2yEgT1DwbAspX9GSQzuyoV+Qgy0MEOTz88ABHfJj/+SCLO+O8bkX1B7fyPX+FjN9K9NHE72yQxSh0taD55nsqI1SCW64qhJVlz+HYVHKE1WGDMUMrhRIIIFuxw1Nqd9RtVezJ+5Q5Rd/Okj2MS21mWndZL+fWCGlpcPGI1zDOXntHZkgOeQbre8DfQuAZuGd5EeAZm2Ac1sFS8QLcE="

  sonarqube:
    depends_on:
      - jenkins
    container_name: sonarqube
    image: sonarqube:9.2.4-community
    ports:
      - "9000:9000"
    restart: always

  selenium_hub:
    container_name: selenium_hub
    depends_on:
      - jenkins
    image: selenium/hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    restart: always

  selenium_node:
    container_name: firefox
    depends_on:
      - selenium_hub
    image: selenium/node-firefox
    environment:
      SE_EVENT_BUS_HOST: "selenium_hub"
      SE_EVENT_BUS_PUBLISH_PORT: "4442"
      SE_EVENT_BUS_SUBSCRIBE_PORT: "4443"
    restart: always