jenkins:
  securityRealm:
    local:
      users:
        - id: "panda"
          password: "panda"
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:panda"
  numExecutors: 0

  nodes:
  - permanent:
      labelString: "agent"
      launcher:
        ssh:
          credentialsId: "jenkins_agent"
          host: "192.168.44.44"
          port: 2222
          sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"
      name: "agent"
      remoteFS: "/home/jenkins/agent"
      retentionStrategy: "always"
      
credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          id: "artifactory"
          username: "admin"
          password: "password"
          scope: GLOBAL

      - basicSSHUserPrivateKey:
          description: "Konto zrobione custom"
          id: "jenkins_agent"
          privateKeySource:
            directEntry:
              privateKey: |
                -----BEGIN OPENSSH PRIVATE KEY-----
                b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
                NhAAAAAwEAAQAAAYEA5LbZqSg62Dliigiy4c7SKQVTJQJk4+PD7MczxIPZLgDTPiQuuHtM
                Gg8FPBJwO0GBJqHDzVca31+1sTWQOAd3rq9w20w3z36NoIIGQc2wKnRA1CO8x4eFQSoE7Z
                nCZfSQ/VOc+Xr+qL6bh90qfGnBpeAK/4wraDI3uQX8yTpO+HFxW70KZHVuRCaboqYmYWR4
                cS2RkcXppIPKJNhIzeWLOl88JzGmKdG6/bCQ7TqiYuPtAKsa8W0lhI2+eHqAceoXg7UtdD
                u9eLLcRfJ1NQYENLHHWAAre/p6OcAsAR2DyImIr79shIE9Q8GwLKV/RkkM7sqFfkIMtDBD
                k8/PAAR3yY//kgizvjvG5F9Qe38j1/hYzfSvTRxO9skMUodLWg+eZ7KiNUgluuKoSVZc/h
                2FRyhNVhgzFDK4USCCBbscNTanfUbVXsyfuUOUXfzpI9jEttZlp3WS/n1ghpaXDxiNcwzl
                57R2ZIDnkG63vA30LgGbhneRHgGZtgHNbBUvEC3BAAAFiO+fjQ3vn40NAAAAB3NzaC1yc2
                EAAAGBAOS22akoOtg5YooIsuHO0ikFUyUCZOPjw+zHM8SD2S4A0z4kLrh7TBoPBTwScDtB
                gSahw81XGt9ftbE1kDgHd66vcNtMN89+jaCCBkHNsCp0QNQjvMeHhUEqBO2ZwmX0kP1TnP
                l6/qi+m4fdKnxpwaXgCv+MK2gyN7kF/Mk6TvhxcVu9CmR1bkQmm6KmJmFkeHEtkZHF6aSD
                yiTYSM3lizpfPCcxpinRuv2wkO06omLj7QCrGvFtJYSNvnh6gHHqF4O1LXQ7vXiy3EXydT
                UGBDSxx1gAK3v6ejnALAEdg8iJiK+/bISBPUPBsCylf0ZJDO7KhX5CDLQwQ5PPzwAEd8mP
                /5IIs747xuRfUHt/I9f4WM30r00cTvbJDFKHS1oPnmeyojVIJbriqElWXP4dhUcoTVYYMx
                QyuFEgggW7HDU2p31G1V7Mn7lDlF386SPYxLbWZad1kv59YIaWlw8YjXMM5ee0dmSA55Bu
                t7wN9C4Bm4Z3kR4BmbYBzWwVLxAtwQAAAAMBAAEAAAGALca/J9Eqfe52X4RAMVvQym8LZi
                Plh4slwrVYEiQFiuSVYyGgzEG5SJnrBUv3dJS2wcGsy+N8OGsSlYZP+DbeaHMq1mmZ3gjJ
                Ve/QSsldUhH0i8EfXpwsOo+rbtbQhtF9V4atq21HnQSRYo8Mmtwb6xQ9f0pRwcgTSQ/+uV
                PXTHiAJMlgVB0A1dkYW2R/2Axg4t4o/ZEsI0ZRZjB32eXwiN1Yz8trI4GbuHzndOPAbqSJ
                4hFdEiczVCV+kuSJ4sLkUwIv5Uw/KcrhkYDVMN/zf3TYCSAX1Vi24PnKFshbuRgHS2MCx8
                WSFGS1885KAFLZ+q8a68aFfFkv3nD9sqTdPS5HzO2ML7FhRX5kutqruK3sCLG/a9cZRkGC
                Skl4092WUIEbrjWvVz7WulItUPqHg266G2hly/Gjyo5T0ptlEBUHwfxX7A9cbqLp+VlXUh
                dPLlYhd6aCmPOdPIF265Q6BagCtQbG7R+lqMEQpZRoGpaP+AXlktE8sNjHU4GQeMW1AAAA
                wQDhAo3L6g3tjTbBO2UIjB9+/qTVQYtKp7+MLqP29qJSgM7lkkxbI+9gd3F0T5NaomKc0c
                kw7bSQyl7qOPNzZuI0ywWAHvUEhZx4YdAydvkXtb/WDypNdZJ+xZ/JyvzpG2MX3CSXuf8c
                B+lVWE76432thZ6y7HWEyuW+jbAL5m+hr7gg9gjq/tm23NJYtVFuehUp98kpQ0JoKAjAKL
                Es/PL31G4BBpP/UgGyzU0gNkJtZhoV+WKUijAPsVPjqIVRqIUAAADBAPv+p+b0JGL3ReME
                OIYCPfzi1RuBEitgFJB6ZWcsUJ4iRNwUSsSMJ54/g900uN9VYnae2B1tTVV3e4ZfOOeUrW
                2hJS7e89QoQvVmy09tRMEY8guYU+PhUcFx13LiKMY6UvkH2/BhM4CZCVJQwSgIRwmAY/Zi
                6ln3LYKOnH5YFgw6exmnVS/t6fX6w8NqYwnea7txn/XOBt+fnqxaBwhE/aWsql3BJa0pyQ
                lx+4znycDRy/+3kK5x9JnGCaIAgbDCxwAAAMEA6Fl313qvAFd1v0GPQ6ucOs6p1IJb5akg
                twTNtrh0f6Mxah3O9uPQseLaE5kFqcecYzBFeVDZT2hZXHwoL0yardWUUYhiOs47X32okg
                5Y4s8mTZ3LTt9vKMGywpHjsC7LZrcu+EXJUncYZPsJrEgED/tzr4958RrbYyrcW3hXuvzD
                E7NK2w9V/qC5uaMAmV7QZE8h0R2jRx/+PBRUmPvaFb43u35pVCA+He84xBRkaR1CStsjQl
                NAISR6YbUzwgM3AAAADXBhbmRhQHZhZ3JhbnQBAgMEBQ==
                -----END OPENSSH PRIVATE KEY-----
          scope: GLOBAL
          username: "jenkins"
          
jobs:
    - file: /usr/share/jenkins/ref/jobs/app_of_apps.groovy
    - file: /usr/share/jenkins/ref/jobs/backend.groovy
    - file: /usr/share/jenkins/ref/jobs/frontend.groovy
          
tool:
  sonarRunnerInstallation:
    installations:
    - name: "SonarQube"
      properties:
      - installSource:
          installers:
          - sonarRunnerInstaller:
              id: "4.7.0.2747"

unclassified:
  locale:
    systemLocale: en
    ignoreAcceptLanguage: true
  location:
    url: "http://192.168.44.44:8080/"
  
  sonarGlobalConfiguration:
    buildWrapperEnabled: true
    installations:
    - name: "SonarQube"
      serverUrl: "http://192.168.44.44:9000"
      triggers:
        skipScmCause: false
        skipUpstreamCause: false

  terraform:
    installations:
    - name: "Terraform"
      properties:
      - installSource:
          installers:
          - terraformInstaller:
              id: "1.4.4-linux-amd64"




      
